### ISSUE TITLE
Can't get this working with executable installed Plex

### ISSUE THREAD

**Issue by JesseWebDotCom** [sarendsen/replex#32]
I have plex installed on Windows (not docker, exe installed) with a static IP of 192.168.1.12. I have replex running in docker on the same windows computer. I have set the "Custom server access URLs" to the following (and restarted plex each time):
* http://127.0.0.1:3001
* http://localhost:3001
* http://192.168.1.12:3001

Not only is there nothing changed in plex but there are also no new lines display in the terminal window when I compose up replex:
```
D:\docker\replex>docker compose up
[+] Running 2/2
 - Network replex_default  Created                                                                                 0.8s
 - Container replex        Created                                                                                 0.1s
Attaching to replex
replex  | 2023-08-11T17:05:12.657049Z  INFO replex: Replex version 0.9.1
replex  | 2023-08-11T17:05:12.680578Z  INFO salvo_core::server: listening [HTTP/1.1] on http://0.0.0.0:80
```

Here is my replex docker compose:
```
version: "3"
services:
  replex:
    image: ghcr.io/sarendsen/replex:latest
    container_name: replex
    environment:
      REPLEX_HOST: http://192.168.1.12:32400
    ports:
      - 3001:80
    restart: unless-stopped
```

I have PMM running perfectly on the same system.

**Comment by JesseWebDotCom** [comment]
The browser says "waiting for localhost" for about 30 seconds and then this displays in the browser window:
```
500: Internal Server Error
The server encountered an internal error while processing this request.
There is no more detailed explanation.
salvo
```

and this displays in the terminal window:
```
replex  | 2023-08-11T17:12:17.193407Z ERROR salvo_proxy: get response data failed error=Other(reqwest::Error { kind: Request, url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Ipv4(192.168.1.12)), port: Some(32400), path: "/", query: None, fragment: None }, source: TimedOut }) uri=http://192.168.1.12:3001/
```

**Comment by JesseWebDotCom** [comment]
tried changing the replex_host value as you instructed - no changed. also tried changing container's network to bridge and put it on its own network - no change.

**Comment by JesseWebDotCom** [comment]
Was able to add the firewall rule by opening powershelll in admin mode and then running your command. tore down and rebuilt container, restarted plex - no change.  here's my latest compose file:
```
version: "3"
services:
  replex:
    image: ghcr.io/sarendsen/replex:latest
    container_name: replex
    environment:
      # REPLEX_HOST: http://192.168.1.12:32400
      REPLEX_HOST: http://host.docker.internal:32400/
      # REPLEX_HOST: http://172.17.0.1:32400
    ports:
      - 3001:80
    restart: unless-stopped
    # network_mode: bridge

#     networks:
#         - shared    

# networks:
#   shared:
#     external: false
```
